//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub full_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub phone_number: String,
    pub profile_url: Option<String>,
    pub password: String,
    pub is_active: Option<bool>,
    pub is_superuser: Option<bool>,
    pub is_verified: Option<bool>,
    pub is_deleted: Option<bool>,
    pub is_online: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
